# Generated by Django 6.0.5 on 2026-05-12 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SDCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('capacity_gb', models.PositiveIntegerField()),
                ('tbw_limit_tb', models.FloatField(help_text='Manufacturer TBW rating in terabytes')),
                ('installed_at', models.DateTimeField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sdcards', to='api.device')),
            ],
        ),
        migrations.CreateModel(
            name='AlertThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warn_at_percent', models.FloatField(default=80.0)),
                ('critical_at_percent', models.FloatField(default=95.0)),
                ('sdcard', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.sdcard')),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('warn', 'Warning'), ('critical', 'Critical')], max_length=10)),
                ('message', models.TextField(blank=True)),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged', models.BooleanField(default=False)),
                ('sdcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='api.sdcard')),
            ],
        ),
        migrations.CreateModel(
            name='WriteEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bytes_written', models.BigIntegerField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('sdcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='write_events', to='api.sdcard')),
            ],
        ),
    ]
