# Generated by Django 6.0.5 on 2026-05-17 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sdcard',
            name='pe_cycles',
            field=models.PositiveIntegerField(default=3000, help_text='Program/Erase cycles supported (e.g. 3000 MLC, 1000 TLC, 100000 SLC)'),
        ),
        migrations.AddField(
            model_name='sdcard',
            name='write_amplification_factor',
            field=models.FloatField(default=1.5, help_text='Typically between 1.0 and 3.0'),
        ),
    ]
