# Generated by Django 6.0.5 on 2026-05-17 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_sdcard_pe_cycles_sdcard_write_amplification_factor'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='latitude',
            field=models.FloatField(blank=True, help_text='GPS latitude e.g. 44.4268', null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='longitude',
            field=models.FloatField(blank=True, help_text='GPS longitude e.g. 26.1025', null=True),
        ),
    ]
